package vln.com.leaderboard;

import java.io.*;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class Leaderboard implements Serializable {
    // Note: No explicit serialVersionUID; auto-generated by Java.
    // Changing class structure may break existing leaderboard.dat.
    private final List<Record> records;

    public record Record(String username, int score, String mapName) implements Serializable {
        // Note: No explicit serialVersionUID; auto-generated by Java.
    }

    public Leaderboard() {
        records = new ArrayList<>();
    }

    public void addRecord(String username, int score, String mapName) {
        records.removeIf(record -> record.username().equals(username));
        records.add(new Record(username, score, mapName));
        records.sort(Comparator.comparingInt(Record::score).reversed());
    }

    public List<Record> getTopRecords(int limit) {
        return records.stream().limit(limit).toList();
    }

    public void saveToFile() throws IOException {
        File dir = new File("src/main/resources/leaderboard/");
        if (!dir.exists() && !dir.mkdirs()) {
            throw new IOException("Failed to create leaderboard directory");
        }
        try (ObjectOutputStream oos = new ObjectOutputStream(
                new FileOutputStream("src/main/resources/leaderboard/leaderboard.dat"))) {
            oos.writeObject(this);
        }
    }

    public static Leaderboard loadFromFile() throws IOException, ClassNotFoundException {
        File file = new File("src/main/resources/leaderboard/leaderboard.dat");
        if (!file.exists()) {
            return new Leaderboard();
        }
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file))) {
            return (Leaderboard) ois.readObject();
        }
    }
}